stages:
    - test
    - build
    - push
    - deploy

test_java:
    stage: test
    image: maven:3.9-eclipse-temurin-17

    script:
      - echo "testing..."    
      - mvn test

build_java:
    stage: build
    image: docker:latest
  
    services: 
      - docker:dind     
    script: 
      - docker build -t $CI_REGISTRY_IMAGE:latest .

push_java:
    stage: push
    image: docker:latest

    services: 
      - docker:dind    

    script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker push $CI_REGISTRY_IMAGE:latest

deploy_java:
    stage: deploy
    script: 
      - echo "deployinggg...
